apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: repartition-job
  namespace: default
spec:
  volumes:
    - name: ivy
      emptyDir: {}
  sparkConf:
    spark.jars.packages: "org.apache.hadoop:hadoop-aws:3.3.6,org.apache.spark:spark-avro_2.12:3.5.0,org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.0"
    spark.driver.extraJavaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp"
    spark.kubernetes.allocation.batch.size: "10"
  hadoopConf:
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    fs.s3a.aws.credentials.provider: com.amazonaws.auth.InstanceProfileCredentialsProvider
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "apache/spark-py:latest"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: s3a://cs598sparkjobs/pyspark-example.py
  arguments: ['172.31.41.192:9092']
  sparkVersion: "3.4.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "4g"
    labels:
      version: 3.0.1
    serviceAccount: spark
    # securityContext:
    #   fsGroup: 65534
    volumeMounts:
      - name: ivy
        mountPath: /tmp
  executor:
    cores: 1
    instances: 1
    memory: "2g"
    labels:
      version: 3.0.1
    volumeMounts:
      - name: ivy
        mountPath: /tmp